### PR TITLE
feat: landing-page

### PR DESCRIPTION
**Pull request by BelideNikhil**

### CODE REVIEW

**Review by techieshubham30 — APPROVED** [review]

**Review by manojasarsa — APPROVED** [review]
Hey Nikhil, It looks good! Just a small suggestion, if you can increase the font-size of heading little bit more, it will look more amazing (as there is much space available).

**Comment by BelideNikhil** [comment]
Thanks for the suggestion Manoj!
I'll do that.

**Comment by preethasri** [comment]
Hey nikhil . The page is different and unique good to go

**Comment by BelideNikhil** [comment]
> Hey nikhil . The page is different and unique good to go

Thanks Preetha!

**Pull request merged**
